default_platform(:ios)

platform :ios do

  desc "Sertifikalari senkronize et"
  lane :sync_certs do
    app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_content: ENV["ASC_KEY_CONTENT"]
    )
    match(
      type: "appstore",
      app_identifier: "com.mcertuzun.game01",
      readonly: false
    )
  end

  desc "TestFlight'a yukle"
  lane :beta do
    app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_content: ENV["ASC_KEY_CONTENT"]
    )
    match(
      type: "appstore",
      app_identifier: "com.mcertuzun.game01",
      readonly: true
    )
    update_code_signing_settings(
      use_automatic_signing: false,
      path: "Builds/iOS/Unity-iPhone.xcodeproj",
      team_id: "Z89P7J7APY",
      targets: ["Unity-iPhone"],
      bundle_identifier: "com.mcertuzun.game01",
      profile_name: "match AppStore com.mcertuzun.game01",
      code_sign_identity: "Apple Distribution"
    )
    update_code_signing_settings(
      use_automatic_signing: true,
      path: "Builds/iOS/Unity-iPhone.xcodeproj",
      team_id: "Z89P7J7APY",
      targets: ["UnityFramework"]
    )
    gym(
      project: "Builds/iOS/Unity-iPhone.xcodeproj",
      scheme: "Unity-iPhone",
      export_method: "app-store",
      output_directory: "Builds/iOS",
      output_name: "GameDeployTest.ipa",
      xcargs: "CODE_SIGN_STYLE[sdk=iphoneos*]=Manual DEVELOPMENT_TEAM=Z89P7J7APY",
      export_options: {
        method: "app-store",
        teamID: "Z89P7J7APY",
        provisioningProfiles: {
          "com.mcertuzun.game01" => "match AppStore com.mcertuzun.game01"
        }
      }
    )
    pilot(
      ipa: "Builds/iOS/GameDeployTest.ipa",
      skip_waiting_for_build_processing: true,
      notify_external_testers: false
    )
  end

end
