default_platform(:ios)

platform :ios do

  desc "Sertifikalari senkronize et"
  lane :sync_certs do
    app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_content: ENV["ASC_KEY_CONTENT"]
    )
    match(
      type: "appstore",
      app_identifier: "com.mcertuzun.game01",
      readonly: false
    )
  end

  desc "TestFlight'a yukle"
  lane :beta do
    app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_content: ENV["ASC_KEY_CONTENT"]
    )
    match(
      type: "appstore",
      app_identifier: "com.mcertuzun.game01",
      readonly: true
    )
    pilot(
      ipa: "Builds/iOS/GameDeployTest.ipa",
      skip_waiting_for_build_processing: true,
      notify_external_testers: false
    )
  end

end
